#!/usr/bin/env bash
# Installs (or removes) an optional pre-commit hook that runs the C0 PII/secret
# scanner on staged files. Fail-closed: BLOCK findings abort the commit.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOK="${ROOT}/.git/hooks/pre-commit"

usage() {
    echo "Usage: $0 [--install|--uninstall]" >&2
    exit 1
}

MODE="install"
if [[ $# -gt 1 ]]; then
    usage
fi
if [[ $# -eq 1 ]]; then
    case "$1" in
        --install) MODE="install" ;;
        --uninstall) MODE="uninstall" ;;
        *) usage ;;
    esac
fi

if [[ "${MODE}" == "uninstall" ]]; then
    if [[ -f "${HOOK}" && "$(head -1 "${HOOK}")" == "#!/usr/bin/env bash" && -n "$(grep -F 'c0_scan.py --staged' "${HOOK}" || true)" ]]; then
        rm -f "${HOOK}"
        echo "Removed pre-commit hook: ${HOOK}"
    else
        echo "No C0 pre-commit hook installed at ${HOOK}."
    fi
    exit 0
fi

mkdir -p "${ROOT}/.git/hooks"

cat > "${HOOK}" <<'EOF'
#!/usr/bin/env bash
# Generated by scripts/install-pre-commit-hook.sh — do not edit manually.
set -euo pipefail
ROOT="$(git rev-parse --show-toplevel)"
if python3 "${ROOT}/engine/scripts/c0_scan.py" --staged --workspace "${ROOT}"; then
    exit 0
fi
status=$?
echo "Commit blocked: C0 PII/secret scanner found issues in staged files." >&2
echo "Fix the findings or explicitly allow them in engine/c0/allowlist.json." >&2
exit "${status}"
EOF

chmod +x "${HOOK}"
echo "Installed pre-commit hook: ${HOOK}"
